### ISSUE TITLE
info_args() for gdb gives incorrect results

### ISSUE THREAD

**Issue by roxx30198** [IntelPython/numba-dpex#1232]
gdb.info_args() gives incorrect results sometimes. This is an example where it fails, below is an example on what is expected if we run the sequence in gdb. For reproducing it locally try running comment out line:60 of test_info.py
ONEAPI_DEVICE_SELECTOR=opencl:cpu pytest test_info.py. It will fail for test_info_args eventually if we run it multiple times.
```
(gdb)set environment NUMBA_OPT 0
(gdb) b side-by-side.py:16
No source file named side-by-side.py.
Make breakpoint pending on future shared library load? (y or [n]) y
Breakpoint 1 (side-by-side.py:16) pending.
(gdb) r side-by-side.py --api=numba-ndpx-kernel
(gdb) info args
```
expected output for info args is 
```
param_a = 2
param_b = 2
```
but it returns 
`(gdb)`

**Comment by ZzEeKkAa** [comment]
After investigating the issue, it appears that the issue was with calling python's `pexpect.expect()` to catch output from `info locals`. python function was called multiple times instead of calling once with the array input. After the first call buffer was read fully and second call was hanging up the program because expected output was already passed.
