### ISSUE TITLE
NdRange does not produce correct results depending on global size

### ISSUE THREAD

**Issue by ZzEeKkAa** [IntelPython/numba-dpex#1308]
This test fails on windows.

```python
import dpnp
import numpy as np

import numba_dpex as dpex
import numba_dpex.experimental as dpex_exp
from numba_dpex.kernel_api import NdItem

_SIZE = 10

@dpex_exp.kernel
def set_ones_nd_item(nd_item: NdItem, a):
    i = nd_item.get_global_id(0)
    a[i] = 1

a = dpnp.zeros(_SIZE, dtype=dpnp.float32)
dpex_exp.call_kernel(
    set_ones_nd_item, dpex.NdRange((a.size,), (a.size,)), a
)

assert np.array_equal(a.asnumpy(), np.ones(a.size, dtype=np.float32))
```

**Comment by ZzEeKkAa** [comment]
UPD: it fails on linux as well, if _SIZE > 8192

**Comment by diptorupd** [comment]
The problem is in the test code. The `NdRange` created by you `dpex.NdRange((a.size,), (a.size,))` means that you want `a.size` work items in total (global size) and also want `a.size` work items per work group. That means your kernel is launched on exactly one work group. 

The linux error is easy to explain, if your `a.size` is greater than 8192 it exceeds the `max_work_item_sizes1d` for that work group after which the behavior is undefined.

```bash
>>> import dpctl
>>> cd = dpctl.SyclDevice("cpu")
>>> cd.max_work_item_sizes1d
(8192,)
```
My hunch will be that the Windows error also comes up for the same reason. I will test and confirm.

**Comment by ZzEeKkAa** [comment]
After further investigation - it seems to be an issue with github CI. Local tests shows that it behaves the same way on linux and windows.
