### ISSUE TITLE
Precedence of with statement versus njit kwargs

### ISSUE THREAD

**Issue by hameerabbasi** [IntelPython/numba-dpex#318]
There is one side-effect of `with` statements: Their effects propagate down the call stack, even into library code. Consider the following code:

```python
# In library.py
@njit(parallel=False)
def library_func(...):
    ...

# In user.py
with dppl.device_context(gpu):
    ...
    library_func(...)
    ...
```

In this case, if the `with` statement is preferred, the library loses control of what's executed inside `library_func` . Raising an error is okay, IMO, but for this reason, we shouldn't prefer what the `with` statement says.

Personally, I'd be okay with changing the default value of `parallel` to `parallel=unspecified`.

**Comment by diptorupd** [comment]
The design of numba-dpex has been changed to follow the Python Array API's compute-follows-data programming model. As such, the `device_context` is no longer used to specify the offload device. All offload decisions are handled at the typing phase based on whether the `jit` function is operating on [dpnp](https://github.com/IntelPython/dpnp) arrays that have a queue attribute.

Closing as the issue is no longer relevant.
