### ISSUE TITLE
Support `from numba-dppy import numba` and use `numba.jit`

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/numba-dpex#620]
Please, note that Numba does not allow change `compilation pipeline` implicitly. But it allows filling typing system.
Use import substitution like in `modin`, `dpnp` and others - change `import numba` to `from numba-dppy import numba` and use `numba.jit` provided by numba-dppy.

_Originally posted by @PokhodenkoSA in https://github.com/IntelPython/numba-dppy/discussions/613#discussioncomment-1605397_

**Comment by diptorupd** [comment]
numba-dpex 0.20. will add a new `djit` decorator that is dpex's equivalent for `numba.njit`. We do not want to use the suggested approach as there are differences between dpex's `dpjit` and `numba.jit`, dpex only suppots `nopython` mode and the `parallel` options is required to be `True`. Due to this reason, having a different name is essential. Users can use aliases as they need.
