### ISSUE TITLE
Numba-dpex should provide a way for users to determine where execution occurred

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/numba-dpex#667]
It opens a very important question that has been brought up by customers as well. Numba-dpex should provide a way for users to determine where execution occurred. I will look into `pti-gpu`.

_Originally posted by @diptorupd in https://github.com/IntelPython/numba-dppy/pull/598#r752697943_

**Comment by diptorupd** [comment]
Since 0.20 numba-dpex offload is based on the `compute follows data` programming model. The explicit guarantee is that compute happens where the data was allocated. The question of trust as to is the compiler really executing the compute on the right device is still relevant, but the right way to handle the question will be to use external profilers such as pti-gpu or Intel Advisor. 

The enhancement is out of scope for numba-dpex.
