### ISSUE TITLE
numba-dpex and numba are failing to parallelize for range loop in pairwise_distance

### ISSUE THREAD

**Issue by mingjie-intel** [IntelPython/numba-dpex#782]
Both numba and numba-dpex is failing to parallelize pairwise_distance test case in dpbench. The error message is:

>   NumbaPerformanceWarning:
> The keyword argument 'parallel=True' was specified but no transformation for parallel execution was possible.
> 
> To find out why, try turning on parallel diagnostics, see https://numba.readthedocs.io/en/stable/user/parallel.html#diagnostics for help.
> 
> File "reproducer.py", line 5:
> @numba.njit(parallel=True, fastmath=True)
> def pairwise_distance():

A simple reproducer is attached here. 
```
import numba
import numpy as np

@numba.njit(parallel=True, fastmath=True)
def pairwise_distance():

    npoints=2
    dims=3
    X1=np.full((2,3), 1)
    X2=np.full((3,2),1)
    D=np.empty((2,2))

    M = X1.shape[0]
    N = X2.shape[0]
    O = X1.shape[1]
    for i in range(M):
        for j in range(N):
            d=0.0
            for k in range(O):
                tmp = X1[i, k] - X2[j, k]
                d += tmp
            D[i, j] = np.sqrt(d)
    print(D) 

```

**Comment by diptorupd** [comment]
The issue is Numba and dpex's preparfor pass do not identify the loop nest as data-parallel. The ParallelAccelerator loop parallelizer in Numba does not have general-purpose dependence analysis or other capabilities to identify parallel regions. The parallelizer is domain-specific and requires users to code using specific identifiers: NumPy calls, NumPy vector expressions, or prange loops.

As such the behavior described in the issue is as expected.
