### ISSUE TITLE
Numba-dpex complains about local variable as input to numba_dpex.local.array()

### ISSUE THREAD

**Issue by samaid** [IntelPython/numba-dpex#829]
The following code snippet does not work in Numba-dpex 0.19
```python
@numba_dpex.kernel
def local_array(a):
    ls = numba_dpex.get_local_size(0)
    b = numba_dpex.local.array(ls, dtype=numba.float32)  # <- Complains that ls must be constant
```

**Comment by diptorupd** [comment]
The original design with `dpex.local.array` had a design limitation that at the local memory allocation had to be compile time constant. This is in line with C99 and OpenCL semantics. In the test code, `ls` or the local range's size is not a compile time constant and as such the error is the expected behavior.

However, numba-dpex now has a new design for local memory allocation in line with SYCL and a `__local` pointer argument in OpenCL. Local memory definition is now to be done outside the kernel and passed in as a kernel argument. By doing so, the local memory allocation can be parameterized based on NdRange local size that is known at kernel launch time.

The new code will look something like this:

```python
@numba_dpex.kernel
def local_array(nditem, a, slm):
    ...

local_size = 64
a = dpnp.ones(1024)
slm = kernel_api.LocalAccessor(local_size, dtype=dpnp.float32)
numba_dpex.call_kernel(local_array, numba_dpex.NdRange((256,),(local_size,)), a, slm) 
```
